window.CODEX = window.CODEX || [];
window.CODEX.push({
  id: "souls",
  title: "Souls",
  heading: "What is a soul?",
  banner: "assets/Aghor.png",
  blocks: [
    { type: "p", text: "On Elorae, \u2018The Infinite\u2019 is the magical framework that suffuses all matter and is responsible for physics and the passage of time. You can think of the Infinite as an invisible force that is within everything, animate or inanimate. From the Infinite, the shapers of Elorae - the Rogue Ancients - created everything. Included in their creations were sentient life." },
    { type: "p", text: "Sentience: conscious or responsive awareness of surroundings, capable of sensory perception and feeling" },
    { type: "p", text: "Sentience brings forth a particular occurrence from the Infinite. Where sentience is found, a soul is created, and without a soul, there is no sentience. As the Infinite invisibly suffuses all of the world, so too does a soul invisibly suffuse a sentient creature. This means that all manner of animals, monsters, and creatures that are sentient carry a soul. When a creature dies, it\u2019s soul is returned to the Infinite. Many cultures have different explanations for the afterlife. The art of Spirit magic attempts to connect to the Infinite to rebuild and commune with the faded souls of the deceased - in this art, restructured souls in the Infinite are called spirits and interact as the spells of the Spirit magician conduct." },
    { type: "p", text: "Souls and the Infinite are inextricably linked and tethered. This means that all souls are technically connected to each other, too. Souls can grow in vitality from how they interact with other souls. For example, a king who has the hearts of his people will have a richer soul than an outland hermit. Essentially, the kings soul has been empowered by the connection created with the souls of his people. His people think of him regularly and may perform acts in service to him, which causes his soul to gain vigor. On the contrary, if he were to be reviled by many, feared, or responsible for the death of many, his soul would also gain vigor. Another example may be that of a group of heroes who slay a monster that is terrorizing a village. The monster has a vigorous soul, as it\u2019s reign of terror is affecting many other souls. When it dies, it\u2019s vigorous soul is returned to the Infinite, and the souls of the heroes grow in kind. Again, a soul grows in vitality from how they interact with other souls." },
    { type: "p", text: "Souls are directly connected with the aging of a creature. The soul, at a baseline, naturally withers away (a lifespan of birth and death). The more rich and vigorous the soul, the longer ones life may be. However, this does not mean everyone who leads a great and cherished life, or every villain who oppresses others may live forever. It takes an extraordinary amount of soul vigor to extend life far beyond mortal limits (however, Death and Life magic are commonly practiced arts of manipulating the vigor of a soul.) Also, the vigor of ones soul generally affects their magical aptitude, strength, and physical attributes. A powerful soul is able to magically manipulate the Infinite and perform feats of strength beyond the abilities of a common soul." },
    { type: "p", text: "Soul vigor is passed down through bloodlines, but only slightly. While the daughter of a Fire mage may have the aptitude for Fire magic above another without a magical parent, the daughter still must practice and learn on their own to foster their potential. Vigor through lineage does not guarantee every generation to be as vigorous or equivalent to the last - each individual still must grow their vigor naturally, they just might be more adept to the arts of their forebears." },
    { type: "p", text: "What is divinity?" },
    { type: "p", text: "A soul may become so bountiful in vigor that it may undergo the process of ascension. When a soul ascends, its connection with the Infinite becomes unimaginably powerful. An ascended soul is referred to as a Divine soul, thus divinity. Those who have ascended are referred to as Divines, Deities, or Gods. A Divine soul is eternal and unaffected by the natural process of age. They are simply too vigorous too wither. When confronted with the path of ascension, it is an innate feeling - an intuitive choice that is indescribable to those who have not experienced it. Ascension to divinity fundamentally transforms ones soul and physical being - many emotions and mortal thoughts become lost, and ones connection to the physical world becomes permanently altered. One capable of ascension may choose to deny it, and live and die as a lesser soul without becoming a Divine - such as the Great Lady Demethine of the Fourth Era. It should go without saying, ascension is phenomenally rare." },
    { type: "p", text: "A divine may begin to manipulate and control the Infinite in ways beyond the comprehension of lesser souls. One ascends to Divinity based on their legendary feats or influence over other souls. Nearly all Gods were practitioners of certain magical arts or figures of indomitable might, widespread praise, or rampant disgust. To lesser souls, Divines are gods." },
    { type: "p", text: "Divines are generally worshiped throughout Elorae as deities, with each specific Divine having a domain that embodies their tenets and masteries. For example, Sar Sareen, Divine of renewal, purity, and clarity, was an exalted queen of her land responsible for defeating the manipulative and deceitful Six-Kings, and ending their reign of clouded terror. A Divine may receive prayers and services in their name, which they may respond to. If a Divine oversteps and begins to inflict harm upon the world, it is common that other Divines may attempt to stop them - creating a tenuous and ever-shifting balance." },
    { type: "p", text: "Divine souls cannot be destroyed by mortal means. Only the power of a Divine soul may inflict harm on another Divine soul. A lesser soul simply cannot naturally harm a Divine soul." },
    { type: "p", text: "The Divines are sometimes classified by the magical divisions that they inherit, and may be referred to as Dark Divines, Light Divines, and Primal Divines (sometimes also called Dark, Light, and Primal Divinities). Religions may also be referred to colloquially as 'divinities', for example, it may be said \u201cShe is a follower of the Divinity of Sar Sareen\u201d." },
    { type: "p", text: "However, exceptions exist, and some Divines that inherit traits of mixed magics may be classified as either Dark, Light, and Primal Divines regardless. Divines that may embody Temporality and Dimensionality are generally just referred to as Divines without a descriptor." },
    { type: "p", text: "What is the difference between a Divine and an Ancient?" },
    { type: "p", text: "The Ancients were the shapers of the cosmos and creators of Elorae. The Ancients existed outside of the Infinite, in fact, they created it. For this reason, the Ancients did not have souls akin to the souls found within the creatures of modern day Elorae, they had something greater - among creation scholars, they are known as the Souls of Creation. The ancients were ephemeral entities that had the power of true omnipotence and omnipresence. Only other Ancients could interact on the same level of being and block the actions of another. However, they were individuals and ultimately did still have an individual essence, however incomprehensible it may be." },
    { type: "p", text: "Aghor, the last-surviving leader of the Rogue Ancients who created the world, was brought forth and destroyed by the Godform in a climactic, catastrophic engagement which ended the third age. The Godform believed Aghor, who was then known as \u2018God\u2019, was actively suppressing the Infinite and keeping the true potential of mortals subdued. In truth, Aghor was doing this, for reasons unexplained. The essence of Aghor, known as the God Soul was split tripartite among the Godform (thus the origin of their title). And so, the Infinite was no longer bound by its creator and souls were forever after granted the potential of ascension." },
    { type: "p", text: "The Godform is not a single entity. It is the title of the three legendary lords that slayed the god of the world and divided that \u2018soul\u2019 amongst themselves." },
    { type: "p", text: "Divine souls hold a fraction of the power held by the Ancients and they can never reach the same level. As Divines are gods to mortals, Ancients are gods to Divines." },
    { type: "p", text: "Some extremely rare beings don\u2019t fall into either category, have unique classifications and powers, and still rival the strength of Divines. These wondrous and terrible powers are out there, waiting to be discovered, feared, or worshiped." },
    { type: "p", text: "Heirarchy of power:" },
    { type: "p", text: "Ancients" },
    { type: "p", text: "Divine Souls" },
    { type: "p", text: "Lesser Souls (Mortals)" }
  ]
});
