window.CODEX = window.CODEX || [];
window.CODEX.push({
  id: "lore",
  section: "lore",
  sectionTitle: "Lore",
  title: "Lore",
  heading: "Lore",
  banner: "assets/Silar Scorria.png",
  blocks: [
    { type: "h3", text: "Table of Contents" },
    { type: "list", items: [
      "Bestiary",
      "Tall Tales of the Reach: City of Serpents",
      "Dialogue in Sable, Edition Seven: Year of the Sapling",
      "Glories of Fala",
      "History of the Ages, Volume I",
      "History of the Ages: Volume II",
      "Ilium Legendarium",
      "History of the Ages: Volume III",
      "The Legend of Creation",
      "The Lost Era, Vol II, Yollonde: The Rise, Fall, and Rebirth of a Dynasty",
      "The Lost Era, Vol III, Nischatel: Liberation and Ascension of Nation and Goddess",
      "Megana, our Goddess of Arcane Secrets and Lore Profound",
      "Military History of Nybei III",
      "Musings of an Old Mason",
      "Mysteries of Old",
      "The Nature of the Divines",
      "On Greenmen",
      "Peoples, Cultures, Ways of Life",
      "Philosophical Thoughts and Commentary",
      "The Rites",
      "Twin Fates: Lore of the Celestial Sands",
      "Seasons",
      "Warnings of the Blooded Prophet",
      "Worldly Stories",
      "Words of Promise",
      "The Wretched Tragedy of Elraim"
    ]},
    { type: "h2i", text: "Bestiary" },
    { type: "by", text: "Adventurer Granson Cayle of Mill" },
    { type: "quote", text: "Deep in the frozen expanse of the Burning Tundra, there is said to be a spectral flame, ever-burning with icy warmth. The monsters that thrive there are enchanted with its magic, faintly glowing as they roam the wastes." },
    { type: "h2i", text: "Tall Tales of the Reach: City of Serpents" },
    { type: "by", text: "Fire Song, Great Poet of Dalamand" },
    { type: "quote", text: "Through the low canyon,\ncrimson cooked in the heat of the suns,\ntravel merchants of death\nThose purveyors of bounty and baubles\npurloined from the coffers\nof old kings and royalty entombed\nThrough the low canyon,\ncrimson cooked they walk,\nto the clandestine city of Sarantara\nTo sell their bounty to the Serpent Lords\nfor the price of freedom and fealty\nThrough the low canyon,\ncrimson cooked, they die\nIn the land of the Red Sun,\nelder than the depths of Her victory" },
    { type: "h2i", text: "Dialogue in Sable, Edition Seven: Year of the Sapling" },
    { type: "by", text: "Curte Redwind of Nischatel" },
    { type: "quote", text: "Great Baraid in the cold lands of Andos, currently ruled by Mountain-King Gralloch Skybane, stands as an everlasting monument of strength and will against all enemies. No invading force, in all of recorded history, have ever breached it's impregnable defenses - not Izil the Firelord in his Age of Flame, nor Horlg's Cleansing - not even the horrific, ancient Dark, which wiped out nearly all of the world's population. Great Baraid has stood firm against all. However, due to this invincibility, some politicians and court attendees believe the kingdom to be complacent, and a useless ally, even secretly silent and malicious. For what need is there for Baraid to pledge to alliance? They can withstand it all! Alas, I believe that not even the mighty and immortal Fala would be able to break through its legendary gates, and if that were the case, then my musings are irrelevant..." },
    { type: "h2i", text: "Glories of Fala" },
    { type: "by", text: "War-Historian Bernadette Laen of Fala" },
    { type: "quote", text: "In the Dark Age, the Great Forest was brought to ruin by the Demon Kings and Isindil burned. The burning of the world tree awoke the ancient dragon god of old, Salaseth, from his slumber in High Shasir. It is said, our great lord, Gadros, God-King of Fala, Undefeated Champion and Ruler of our Immortal Kingdom, rode the world-drake into battle, uniting the old Helfaust Clans and Invincible Legion of the mountain under a single banner against the demonic lords." },
    { type: "quote", text: "The Aegis of Fala is an enchanted shield used by an ancient god in the wars against the Dark. It now rests above the Immortal Throne, alongside other artifacts of incredible power." },
    { type: "quote", text: "The waters flow gently down the river Dine,\nto the land of Kings, mighty in their reign\nand lofty sat in their immortal throne,\nexalted by the divine\nThe waters flow gently down the river Dine\nby where the blood of Eren fed the roots,\nof the oaks that stood and watched\ngreat empires fall and rise\nThe waters flow gently down the river Dine,\nof which the muds bank, walked on by\nscores of voyagers, their feet leaving prints\nfleeting with time\nNamed of the Lady White, by whose purity\nthe people were graced and were from\nthe shadow led - to be blessed\nby the light that shines,\nsparkling on the water\nof the river Dine,\nwhere the waters flow gently" },
    { type: "h2i", text: "History of the Ages, Volume I" },
    { type: "by", text: "Kept by the Scribes of Valoris" },
    { type: "quote", text: "Agal's Rock in the Lost Age was used as a shamanic meeting ground for the clans of the Helfaust in their alliance against the World-Beast. Eventually, it became known as Deathrock, and the Battle of Deathrock blasted the landscape around it. Only now, in the new age, has greenery begun to return to its surroundings. Only the tip of the once mighty stone is now visible, an old survivor of war returning to the soil." },
    { type: "quote", text: "The most fearsome, monstrous beasts on all of Elorae roam the plains of Awakul, the Land of Giants. The untamed wilds were once broken and scarred by ages of war, but when the Infinity washed over the landscape, life bloomed thrice over. The bravest warriors and hunters traveled to the land hearing tales of the gargantuan monsters, seeking fame and glory in the hunt. Centuries later, Dhar Awakul, the Great Kingdom of the High Hunters, stands tall over the plains - it's massive walls adorned with the skulls and bones of the primal world." },
    { type: "quote", text: "... and when the great kingdoms of Fala and Myrna united under a single banner, the Helfaust trembled in defeat. Never again would they rise to such might as in the days of The Supremacy. Out of their defeat arose the Kingdom of Morath and those who wished to conserve the ways of yore fled, never to return to the plains of their ancestral home." },
    { type: "quote", text: "The Morathi have come a long way from their savage heritage. Living within the walls of a Great Kingdom, the metropolis of Morath provides comfort, order, and civilized culture to its forty thousand denizens. The Morathi still hold the strength and tenacity of their Helfaust ancestors, however, they have grown refined over decades of imperialism by the Great Kingdoms of the west. Over the ages, they have traveled far and across the realms -to many, they are seen still as dangerous, primal. Yet to most, they are greeted with open arms- either in true respect or for fear of the wrath of Fala or Myrna." },
    { type: "h2i", text: "History of the Ages: Volume II" },
    { type: "by", text: "Kept by the Scribes of Valoris" },
    { type: "quote", text: "Nowhere in all the world is there such natural comfort than in the great land of Syr Sable. Its idyllic region of Estic Orne is filled with rolling green fields of pastoral beauty and farm villages at peace. The mighty Fala and the great kingdoms of the world acknowledge its neutrality, and leave it alone with respect to its history." },
    { type: "h2i", text: "Ilium Legendarium" },
    { type: "by", text: "Miriem Benedath, Historian of Aratta Tum" },
    { type: "quote", text: "When the Eren Dominion marched northward out of Ala Nahri on their genocidal conquest, they came out of the desert wastes upon the sparkling waters of the Kingdom of Aghoras. The Dominion, drunk on the blood of the Samafites, entered the territory and prepared for their next victory. However, they were undeniably bewildered when the cities and villages they knew to exist had vanished. The High Sorcerers of Aghoras, the magical masters of the old ways, phased the kingdom out in its entirety - as they knew they could not withstand the onslaught of the blooddrunk army. And so the Dominion continued on, with newfound caution, to meet the Golossian Kings on the northern battlefields - and ultimately, writhe in defeat at the hands of Krael, the Mighty and Immortal." },
    { type: "h2i", text: "History of the Ages: Volume III" },
    { type: "by", text: "Kept by the Scribes of Valoris" },
    { type: "quote", text: "After the Great Collapse came the Deep Withering, when the leylines ran dry. It was then soon after that the ashborne people enslaved the deepfolk and erected their central Kingdom of Yn'rylith. And from this atrocity birthed the unending Spawn Wars, which perpetuate a millenia later, unto this very day." },
    { type: "quote", text: "It began in IV-2150, when the Mad Wizard-King of Angham, Horlg the Vile, commanded the city-gates to be chained shut, and his apothecaries to test their abominable, toxic concoctions upon his own people. In the demented horror, it is said the King waded into the market square and ensorcelled himself while basking in the screams of the afflicted. Come morning, the gates opened once again, and the infected survivors, now thralls of the King, were unleashed upon the land to spread their horrid pestilence." }
  ]
});
