window.ENTRIES = [
  {id:"aghor", title:"Aghor", caption:"(UH-gorr) · Ancient of Time and Space", image:"assets/Aghor.png", tags:["figures"], fit:"cover", position:"center", lore:["The Creator, The Infinite, The God Soul, God.","Rogue Ancient said to have come from the Timeless Void to create the world. Creator of Time and Space, mortal souls, and the Infinite. Destroyed by the terrible power of the Godform, to whom the God Soul was absorbed, tripartite."]},
  {id:"ashforge-kuroishi", title:"Ashforge Kuroishi", caption:"", image:"assets/Ashforge Kuroishi.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"aszurithice-human", title:"Aszurithice, Human Form", caption:"", image:"assets/Aszurithice, Human Form.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"aszurithice", title:"Aszurithice", caption:"", image:"assets/Aszurithice.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"auralon", title:"Auralon", caption:"", image:"assets/Auralon.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"baiji", title:"Baiji", caption:"", image:"assets/Baiji.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"bel-harath", title:"Bel Harath", caption:"", image:"assets/Bel Harath.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"cadarinost-falls", title:"Cadarinost Falls", caption:"", image:"assets/Cadarinost Falls.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"caurobor", title:"Caurobor", caption:"", image:"assets/Caurobor.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"curse-of-olesh", title:"Curse of Olesh", caption:"", image:"assets/Curse of Olesh.png", tags:["relics"], fit:"cover", position:"center", lore:[]},
  {id:"cursed-of-olesh", title:"Cursed of Olesh", caption:"", image:"assets/Cursed of Olesh.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"darmstadt", title:"Darmstadt", caption:"", image:"assets/Darmstadt.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"elraim", title:"Elraim", caption:"", image:"assets/Elraim.jpg", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"filibeth", title:"Filibeth", caption:"The white woman of the red wood", image:"assets/Filibeth.png", tags:["figures"], fit:"cover", position:"62% 20%", lore:[]},
  {id:"galands-first-flight", title:"Galand's First Flight", caption:"", image:"assets/Galand's First Flight.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"haethlin-dream", title:"Haethlin in the Dream", caption:"", image:"assets/Haethlin in the Dream .png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"haethlin", title:"Haethlin", caption:"", image:"assets/Haethlin.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"hanto-han", title:"Hanto Han", caption:"", image:"assets/Hanto Han.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"heldranc-flies", title:"Heldranc Flies", caption:"", image:"assets/Heldranc Flies.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"heldranc-human", title:"Heldranc, Human Form", caption:"", image:"assets/Heldranc, Human Form.webp", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"hesk", title:"Hesk", caption:"", image:"assets/Hesk.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"horde-of-olesh", title:"Horde of Olesh", caption:"", image:"assets/Horde of Olesh.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"imani-valash", title:"Imani Valash", caption:"", image:"assets/Imani Valash.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"ito-gangara", title:"Ito Gangara", caption:"", image:"assets/Ito Gangara.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"karanaro-tenbu", title:"Karanaro Tenbu", caption:"", image:"assets/Karanaro Tenbu.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"kojin-redroot", title:"Kojin, in Redroot Village", caption:"", image:"assets/Kojin, in Redroot Village.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"kojin", title:"Kojin", caption:"", image:"assets/Kojin.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"maegoroth", title:"Maegoroth", caption:"", image:"assets/Maegoroth.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"mano", title:"Mano", caption:"", image:"assets/Mano.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"mintas-fae", title:"Mintas Fae", caption:"", image:"assets/Mintas Fae.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"montmorian-rages", title:"Montmorian Rages", caption:"", image:"assets/Montmorian Rages.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"montmorian-alabaster", title:"Montmorian and the Alabaster Blade", caption:"", image:"assets/Montmorian and the Alabaster Blade.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"montmorian-chamber", title:"Montmorian in his Chamber", caption:"", image:"assets/Montmorian in his Chamber .png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"nyralshirad-human", title:"Nyralshirad Human Form", caption:"", image:"assets/Nyralshirad Human Form.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"nyralshirad", title:"Nyralshirad", caption:"", image:"assets/Nyralshirad.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"perstrin-naba", title:"Perstrin Naba", caption:"", image:"assets/Perstrin Naba.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"pethengorom-fate", title:"Pethengorom's Fate", caption:"", image:"assets/Pethengorom's Fate.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"pethengorom-human", title:"Pethengorom, Human Form", caption:"", image:"assets/Pethengorom, Human Form.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"pethengorom", title:"Pethengorom", caption:"", image:"assets/Pethengorom.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"phantom-cavern", title:"Phantom Cavern", caption:"", image:"assets/Phantom Cavern.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"rathalon-ii", title:"Rathalon II", caption:"", image:"assets/Rathalon II.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"revenant-host", title:"Revenant Host", caption:"", image:"assets/Revenant Host.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"salaseth-ii", title:"Salaseth II", caption:"", image:"assets/Salaseth II.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"saoirse-canyon", title:"Saoirse In the Burning Canyon", caption:"", image:"assets/Saoirse In the Burning Canyon.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"saoirse", title:"Saoirse", caption:"", image:"assets/Saoirse.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"sen-teloch-ini", title:"Sen Teloch Ini", caption:"", image:"assets/Sen Teloch Ini.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"silar-scorria", title:"Silar Scorria", caption:"", image:"assets/Silar Scorria.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"sthistu", title:"Sthistu", caption:"", image:"assets/Sthistu.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"through-the-portal", title:"Through the Portal", caption:"", image:"assets/Through the Portal.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"vaerek-at-ease", title:"Vaerek, At Ease", caption:"", image:"assets/Vaerek, At Ease.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"vaerek-heldranc", title:"Vaerek, Vessel of Heldranc", caption:"", image:"assets/Vaerek, Vessel of Heldranc.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"vallorca", title:"Vallorca", caption:"", image:"assets/Vallorca.png", tags:["places"], fit:"cover", position:"center", lore:[]},
  {id:"vehem-adahr", title:"Vehem Adahr", caption:"", image:"assets/Vehem Adahr.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"vorn", title:"Vorn", caption:"", image:"assets/Vorn.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"yena", title:"Yena", caption:"", image:"assets/Yena.png", tags:["figures"], fit:"cover", position:"center", lore:[]},
  {id:"yuo-nanaga", title:"Yuo Nanaga", caption:"", image:"assets/Yuo Nanaga.png", tags:["figures"], fit:"cover", position:"center", lore:[]}
];
