#!/usr/bin/env python3
"""Precompute the Index card-flip art data (art86).

For every articles/<slug>.html, read the main hero art (section.art-hero > img), and
extract a dominant saturated accent plus a darker tone with Pillow:
  - downsample to 128px, drop near-black / near-white / grey pixels,
  - weight each remaining pixel by saturation^2 * value, bin hues into 36 x 10deg bins,
  - take the strongest 3-bin hue window and average those pixels (RGB) -> base colour,
  - clamp in HLS so it stays tasteful and readable on the #0b0b0b panel:
      accent: L 0.56-0.66, S 0.38-0.62   (glow, tint gradient, rules)
      label:  same hue, L 0.74, S <= 0.42 (accent text on dark: dt, epithet, cite...)
      deep:   same hue, L 0.16-0.22, S <= 0.55 (dark end of the tint gradient)
It also writes a tiny copy of the hero art (assets/lore-blur/<slug>.jpg, 128px wide) used as
the heavily blurred frosted-glass backdrop of the flipped card, so the browser never decodes
the multi-MB hero PNG just to blur it. Articles whose art is missing / colourless get no
palette (neutral labels); a missing hero falls back to the card's own image in card-lore.js.
Output: card-lore-palette.js (window.__lorePalette = {slug: {accent, label, deep, hue, art, blur}}).
Run from the repo root:  python3 tools/art-palette.py
"""
import colorsys, json, os, re, sys
from html import unescape
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HERO = re.compile(r'<section class="art-hero[^"]*"[^>]*>\s*<img src="([^"]+)"')


def clamp(x, lo, hi):
    return max(lo, min(hi, x))


def rgb_of(h, l, s):
    return tuple(int(round(c * 255)) for c in colorsys.hls_to_rgb(h, l, s))


def palette(path):
    im = Image.open(path).convert("RGB")
    im.thumbnail((128, 128))
    bins = [[0.0, 0.0, 0.0, 0.0] for _ in range(36)]  # weight, r, g, b
    for r, g, b in (im.get_flattened_data() if hasattr(im, "get_flattened_data") else im.getdata()):
        h, s, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
        if v < 0.18 or s < 0.18 or (v > 0.95 and s < 0.25):
            continue
        w = s * s * v  # favour vivid accents over skin / earth tones
        k = int(h * 36) % 36
        bins[k][0] += w; bins[k][1] += r * w; bins[k][2] += g * w; bins[k][3] += b * w
    total = sum(b[0] for b in bins)
    if total <= 0:
        return None
    best = max(range(36), key=lambda i: bins[i - 1][0] + bins[i][0] + bins[(i + 1) % 36][0])
    win = [bins[best - 1], bins[best], bins[(best + 1) % 36]]
    W = sum(b[0] for b in win)
    if W / total < 0.08 and total < 50:
        return None
    r, g, b = (sum(x[i] for x in win) / W / 255 for i in (1, 2, 3))
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    accent = rgb_of(h, clamp(l, 0.56, 0.66), clamp(s, 0.38, 0.62))
    label = rgb_of(h, 0.74, min(s, 0.42))
    deep = rgb_of(h, clamp(l * 0.4, 0.16, 0.22), min(s, 0.55))
    return {"accent": "%d,%d,%d" % accent, "label": "%d,%d,%d" % label,
            "deep": "%d,%d,%d" % deep, "hue": int(round(h * 360))}


def main():
    out = {}
    adir = os.path.join(ROOT, "articles")
    for fn in sorted(os.listdir(adir)):
        if not fn.endswith(".html"):
            continue
        slug = fn[:-5]
        m = HERO.search(open(os.path.join(adir, fn), encoding="utf-8").read())
        if not m:
            continue
        src = os.path.normpath(os.path.join(adir, unescape(m.group(1))))
        if not os.path.exists(src):
            continue
        p = palette(src) or {}
        p["art"] = os.path.relpath(src, ROOT)
        bdir = os.path.join(ROOT, "assets", "lore-blur")
        os.makedirs(bdir, exist_ok=True)
        im = Image.open(src).convert("RGB")
        im.thumbnail((128, 128))
        im.save(os.path.join(bdir, slug + ".jpg"), "JPEG", quality=82, optimize=True)
        p["blur"] = "assets/lore-blur/%s.jpg" % slug
        out[slug] = p
    js = ("/* Generated by tools/art-palette.py (art86): Index card-flip data per article, from each\n"
          "   article's hero art. accent/label/deep are \"r,g,b\"; blur is the tiny backdrop source\n"
          "   (site-root relative). Do not edit by hand. */\n"
          "window.__lorePalette = " + json.dumps(out, indent=0, ensure_ascii=False, sort_keys=True) + ";\n")
    open(os.path.join(ROOT, "card-lore-palette.js"), "w", encoding="utf-8").write(js)
    for k, v in out.items():
        print("%-18s hue %4s  accent %-12s label %-12s deep %-10s %s" % (k, v.get("hue"), v.get("accent"), v.get("label"), v.get("deep"), v["blur"]))
    print(len(out), "articles", file=sys.stderr)


if __name__ == "__main__":
    main()
